# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a7c94f53fa976e8995da1a9ab591fa34339c9477e7cadb1e5894a2694c10fcc262dc3dd83b94cfd5d1d2d66efcb81ecd72c217282923d0156ea15d173db6418
  s3_access_key_id: AKIAIQUIEKVMIT3RJ37Q
  s3_secret_access_key_id: SBQrU14WEpUDrJ52sF0juf+r1MWOcjSBxXwtOP8S

test:
  secret_key_base: 475c68fbfb133c9fcfd60c0f4f813d5af8643ee6d65d05f4162515aeee951d0663b978ba92b33136adb3704f60fc284c0537ba8b3ac2544adb363708ac5fa0a1
  s3_access_key_id: AKIAIEGZDZMMCRQ3XTKA
  s3_secret_access_key_id: lBvfUwKJKZTXpRj6xhkXNse/V90U4Sp4RvTQ9y4w

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 475c68fbfb133c9fcfd60c0f4f813d5af8643ee6d65d05f4162515aeee951d0663b978ba92b33136adb3704f60fc284c0537ba8b3ac2544adb363708ac5fa0a1
  s3_access_key_id: AKIAIEGZDZMMCRQ3XTKA
  s3_secret_access_key_id: lBvfUwKJKZTXpRj6xhkXNse/V90U4Sp4RvTQ9y4w
